% data = load('fan_temperature.mat');
% vars = fieldnames(data);
% s = data.(vars{1});
% T = struct2table(s);
% F01_temperature_table = T(1:12705, {'test_id', 'fan_id', 'location_id', 'time_sec', 'time_min', 'time_of_day_hours', 'temperature_C'});
% save('F01_temperature.mat', "F01_temperature_table");
% F02_temperature_table = T(12706:25410, {'test_id', 'fan_id', 'location_id', 'time_sec', 'time_min', 'time_of_day_hours', 'temperature_C'});
% save('F02_temperature.mat', "F02_temperature_table");
% F03_temperature_table = T(25411:38115, {'test_id', 'fan_id', 'location_id', 'time_sec', 'time_min', 'time_of_day_hours', 'temperature_C'});
% save('F03_temperature.mat', "F03_temperature_table");
% F04_temperature_table = T(38116:50820, {'test_id', 'fan_id', 'location_id', 'time_sec', 'time_min', 'time_of_day_hours', 'temperature_C'});
% save('F04_temperature.mat', "F04_temperature_table");
% F05_temperature_table = T(50821:63525, {'test_id', 'fan_id', 'location_id', 'time_sec', 'time_min', 'time_of_day_hours', 'temperature_C'});
% save('F05_temperature.mat', "F05_temperature_table");
% F06_temperature_table = T(63526:76230, {'test_id', 'fan_id', 'location_id', 'time_sec', 'time_min', 'time_of_day_hours', 'temperature_C'});
% save('F06_temperature.mat', "F06_temperature_table");
% F07_temperature_table = T(76231:88935, {'test_id', 'fan_id', 'location_id', 'time_sec', 'time_min', 'time_of_day_hours', 'temperature_C'});
% save('F07_temperature.mat', "F07_temperature_table");
% F08_temperature_table = T(88936:end, {'test_id', 'fan_id', 'location_id', 'time_sec', 'time_min', 'time_of_day_hours', 'temperature_C'});
% save('F08_temperature.mat', "F08_temperature_table");